name: Create a pull request to update TonAPI SDK

on:
  push:
    branches:
      - master
      - update-sdk

jobs:
  update_sdk:
    name: Update TonAPI SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Go Version
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: create pull request
        run: make update-sdk
    env:
      GH_TOKEN: ${{ github.token }}
